/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_believe_we_SystemUtils */

#ifndef _Included_com_believe_we_SystemUtils
#define _Included_com_believe_we_SystemUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_believe_we_SystemUtils
 * Method:    getThreadId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_believe_we_SystemUtils_getThreadId
  (JNIEnv *, jclass);

/*
 * Class:     com_believe_we_SystemUtils
 * Method:    getProcessId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_believe_we_SystemUtils_getProcessId
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
